name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache Buildroot build directory
        id: cache-buildroot
        uses: actions/cache@v3
        with:
          key: buildroot-cache
          path: |
            build
      - name: Install required packages
        env:
          LANG: en_US.UTF-8
        run: |
          sudo apt-get update 
          sudo apt-get upgrade -y
          sudo apt-get install -y locales
          sudo localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
          sudo apt-get install -y git build-essential wget cpio unzip rsync bc libncurses5 libncurses5-dev libncursesw5-dev screen file cmake python3 python3-dev python3-setuptools python3-pip
      - if: ${{ steps.cache-buildroot.outputs.cache-hit != 'true' }}
        name: Execute build script
        run: bash ./br_build.sh
      - name: 'Tar files'
        run: tar -cvf buildroot.tar build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: buildroot
          path: buildroot.tar